---
# ------------------------------------------------------------------------
# handlers file for swap
# ------------------------------------------------------------------------

- name: restart swap
  service:
    name: "{{ swap_service }}"
    state: restarted
  when:
    - ansible_virtualization_type != "docker"
